export const ACTIONS = {
  SET_USERS: "SET_USERS",
  SET_USERNAME: "SET_USERNAME",
  SET_IS_SEARCH: "SET_IS_SEARCH",
  SET_IS_NOT_FOUND: "SET_IS_NOT_FOUND",
  SET_REPOS: "SET_REPOS",
  SET_IS_FETCHING: "SET_IS_FETCHING",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
};
